---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1486ecutme9nmhc0zxs5mvna0tay5p0glgcn9tdvkpzjuhm3g0qeszmkp65"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1486ecutme9nmhc0zxs5mvna0tay5p0glgcn9tdvkpzjuhm3g0qeszmkp65"
stores:
  yaml:
    indent: 2
