# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Cfs84H6IsVG/xC7ov5LErb/qbnTpMtRgP71qHGEoXI0=,iv:pNAP4E1XxuDindMAWQfi704CnCsmvdhPNAJypcjUGkk=,tag:YiNgvJNUmckK/fGhhy9P3A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1486ecutme9nmhc0zxs5mvna0tay5p0glgcn9tdvkpzjuhm3g0qeszmkp65
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeW9pbG9mMHM4eGhTM0pr
        SC9VT1BXSFpzWHJsNHQrUTFaemZUNTRjMDNBCnR0WFNua0syWENEY3M2c3dvaWJl
        WmZoK3dYUXB3aDJ4S0RaY3pRaEIwN1EKLS0tIExQb2VqQUpFZmxsKzV3bTJVZGZV
        V2hsNFRHWFZ5SmE4NWs3aXh4Q2MyK0UKQsEPNO/5v+MNyLR3ImHXkwtAKaCc/B3k
        jLKkQHzOygopiLhNUaMtdaG+hVm3GoLsR1oKk5VImzslDos3DQdj0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-10T01:03:40Z"
  mac: ENC[AES256_GCM,data:YX9FxXnioNcDTHvmG8Rmi0EnvQNOT4AUjpU4PVnWkUEDxV9QzSckef6Mst8oLLPdOMTA39NXW91dAR85N1VLNuDv5gwJAMU7c5QvJ3O535G+GvXZ1S4N5rEcx9tGYekDKNJvKWbDGINg2fiMfWnzn1XVuOYACYpw/jC6Au5/Y5U=,iv:BYKhcRAf84aogypmrEDjf8HOP3+e6ZcUwUoH/Q/lWOc=,tag:w5i72twfowDqVeI2MiHb2w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
