# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:pILcH9gpL+ymgL0K9JppUVZdJJwsup8Qsswp47TYXU4s+Sim6rg8Bw==,iv:+RyR1ET/+8yPU+akPNFwq1jwx07qYnxhdPhVQdjaNIc=,tag:5kWgwp+jst34rQUCBlYdWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1486ecutme9nmhc0zxs5mvna0tay5p0glgcn9tdvkpzjuhm3g0qeszmkp65
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eHBzZG4rckpyY2owaEdm
        T3ptZWxzbFpINkNnenVzdXA4YlBvOWFmMGtZCnlIT2lHZWIvUXhCV1NFQTR4ZExj
        WnF6OEtScndCTjlmYnlyTTFLbmlCVVUKLS0tIHRQMXhjd2NXZ0J0L2ZzZFRmRkw2
        S2R1NWxOVm9QWmdBME9hL1RoZnh6a2cKzugDKjWYcVSEawg6IZd+YT6BroS6Avrt
        it2nQv//F8n4pvLPVlNEtyLlSpnITgpVDQdl9E39WoRHEIKqbjn0yA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-10T01:03:40Z"
  mac: ENC[AES256_GCM,data:07RWUEChAKxiJDFOao6eaz2PySbF0nTO1GCErJNzMR5CC17UhTKQt4oGBSNf8P8j9gfk0Onxa8lpnqbXzfF7pY1jI4/3PJTNldSdCjhGNgMiY97+1Jr1TKUMzTYCjb9rxaHwGalUjRMVgBCWubv4LrN8YjEX1L0qXsAxtI5ElAw=,iv:4uFT5F6vYeR3ynU1ybmRdaPB+vsGQDuSP6vgWF0LBJo=,tag:nNrX61F2ettxQ/mJARXicw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
