apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:DGiMb9Aj4ILEEg==,iv:t+kYhD1RhS90p+0G0wpEkMDhYFovG+YRWSenEnw5yQ0=,tag:4mSA6g/DGn2MngPzZM+2Tw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:dcsV5zoJ3W2VkURJZ64T9hzg0bICqU3/zUbb4+LNQAaz+3W7,iv:g1IcjEZGYBeUdEpAivzLTtJHSPYuuW48+fH1IhUxnmg=,tag:I/Fh7V+aQVysr8N3kHvnRQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1486ecutme9nmhc0zxs5mvna0tay5p0glgcn9tdvkpzjuhm3g0qeszmkp65
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQVdTVW9aZVBLWmFGaDds
        dVhUUHcvcmhsbnBzZWZpa0hnU2dKZldxMWg4Cm5VczBrUXFNaXh5ZHF4YXVmaWlU
        aHg1UmpxR051TTdSd2Rna1hEUnJLaWcKLS0tIG1VQWdFUHlqTDk4SkpEQzNObDNG
        eWIzV3BXWTJsQVU2TjVsOE5qSXNLOTgKexjSrVgLaoii0gFxmD89lybteNxtTvAt
        jUYzb473CZmO6GhMwRdZOKxBdtAIeltgFpPhx2RF8YMwDW15x+ZXlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-10T04:23:04Z"
  mac: ENC[AES256_GCM,data:kB13S+mQy9carG5RX3zYt5rWwrq0jquFWvXUbz7wSUZ1lykYb1rc8qotafGa11DUWgzEtB/jCpUk7SyawtzgLzY7iBqPHFLrO8cxznpxyuSZMha7yyLv4VD6lKhCmQG7RDLTWYD+A46QI//kDutb/abvUAw9eeCsJ828KmPsjHs=,iv:yV/GWPx+80dJE7319rXMZoAV6M5e8kv/0ArW6xFnLDE=,tag:TY8Z0OHOG5+5WBoMnxoYNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
