apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:A1kuOo3BFKGoZQ==,iv:qXB+7NCT4DbBLHX81B5mkmpbkoI671unLGgkWGFVsO0=,tag:rMq8A8CHouTuBPOLfn61fg==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qXk4dGgsutSbJkQzX97uGmxFdX7j9tUgdMPEwJfn+g7ZTFrO,iv:tmunpv+xJ1fO2vDdZsygpZze0eZSCqOzHK41gvGdFyg=,tag:PB7VvV4pJi2cIT0zl1M9cg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1486ecutme9nmhc0zxs5mvna0tay5p0glgcn9tdvkpzjuhm3g0qeszmkp65
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmJJNHBtOFN6bUdVM0R5
        bVREOEtNR2V2N1hOdjI0SEhQUENid1M2dmdnCmtLUmdwTkNjTnJxeE5sRzYwdnE3
        Vy9BdEM0TVE2Q05ZQnpPcDBOUmZwQ1UKLS0tIGpCam53b0NTOEUxZ2EyY0dpa1JC
        aFBZYkg5VkdjaVg3S1duK2xNYmxiazAKjY8zH9Q4yb4VZYsqaTewKBPYqSi3qogJ
        ymfidb1cqkSsqngO4ognDb+ZJxA3SqnaFksTm08C6q+B5A8jnuZJwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-10T03:09:11Z"
  mac: ENC[AES256_GCM,data:6RNghNKEHj7l4cSVYqtpC8tsjkVam6xAz/XZUbCiMTMtxnB80bViYsE/HwB/7NZ+bSONOCyyFgEdsxYxUFDPV6Bxk4YkS22hD23lkYkovCXEIEfWNmCBUB2vP7sQjUgLIJPSAXkqms1RGEnS1aWTjaSwbW/sNlwirV2amAitORY=,iv:0eOHqvkANx6n2ydRoD2aX7bzHA4q0hSVHDcIkhw2l6o=,tag:bWkSR+xbQHDK27m3qhfnDA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
